schema=1
version=1.2.8
publishedAt=2026-08-30T12:46:33Z
notesUrl=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/tag/v1.2.8
asset.android.file=SyncDroid-Mesh-1.2.8-Android.apk
asset.android.url=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/download/v1.2.8/SyncDroid-Mesh-1.2.8-Android.apk
asset.android.sha256=653e7338388fa96282b1a8472600a4ae4968800972b3dc07151b24010f60a99b
asset.android.size=55894094
asset.macos-arm64.file=SyncTosh-1.2.8-macOS-arm64.dmg
asset.macos-arm64.url=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/download/v1.2.8/SyncTosh-1.2.8-macOS-arm64.dmg
asset.macos-arm64.sha256=95f37cea5dea5d0866cc6f17cb42caed19cd8423f0f0736a4a13f0569b8a43f1
asset.macos-arm64.size=140077341
asset.windows-x64.file=SyncDows-1.2.8-Windows-x64.exe
asset.windows-x64.url=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/download/v1.2.8/SyncDows-1.2.8-Windows-x64.exe
asset.windows-x64.sha256=892d22b68ea529b2e1b2b7c38f4d6ec9287bab5cfe4f99c738e271cca87df185
asset.windows-x64.size=129144306
