schema=1
version=1.2.10
publishedAt=2026-09-04T23:44:06Z
notesUrl=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/tag/v1.2.10
asset.android.file=SyncDroid-Mesh-1.2.10-Android.apk
asset.android.url=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/download/v1.2.10/SyncDroid-Mesh-1.2.10-Android.apk
asset.android.sha256=f38cf0fd30afa85f89ba3744933d367e3cf03e1482a646d541ceee9ae8b78c71
asset.android.size=55910482
asset.macos-arm64.file=SyncTosh-1.2.10-macOS-arm64.dmg
asset.macos-arm64.url=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/download/v1.2.10/SyncTosh-1.2.10-macOS-arm64.dmg
asset.macos-arm64.sha256=b9e26991f47170dc7ba496f4bf360689aaf7f0054354157784cd1701562e83ac
asset.macos-arm64.size=141854543
asset.windows-x64.file=SyncDows-1.2.10-Windows-x64.exe
asset.windows-x64.url=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/download/v1.2.10/SyncDows-1.2.10-Windows-x64.exe
asset.windows-x64.sha256=969a2111d8c67ac2edfe577ba96870fd65a395553f8bb289ea1e12f63fce858a
asset.windows-x64.size=129194220
