schema=1
version=1.2.16
publishedAt=2026-10-06T04:50:34Z
notesUrl=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/tag/v1.2.16
asset.android.file=SyncDroid-Mesh-1.2.16-Android.apk
asset.android.url=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/download/v1.2.16/SyncDroid-Mesh-1.2.16-Android.apk
asset.android.sha256=55ea5207b130f49dfea43a1411d43f2cf57784d65a83ba5529b069df5d98b471
asset.android.size=59130992
asset.macos-arm64.file=SyncTosh-1.2.16-macOS-arm64.dmg
asset.macos-arm64.url=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/download/v1.2.16/SyncTosh-1.2.16-macOS-arm64.dmg
asset.macos-arm64.sha256=474fd3dc7133e18b0c3f830ba4252e7702fe8990526ec55b640674d5d872bdd5
asset.macos-arm64.size=142030880
asset.windows-x64.file=SyncDows-1.2.16-Windows-x64.exe
asset.windows-x64.url=https://github.com/Fullm3t41/SyncDroid-Mesh/releases/download/v1.2.16/SyncDows-1.2.16-Windows-x64.exe
asset.windows-x64.sha256=0e425be50cb029eddff6e02378649cb589ca24bbb783d7d2001e30f1a37cce6e
asset.windows-x64.size=129344575
